node {

 checkout scm

    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
        dir ('Order') {
          bat 'mvn clean'
            bat 'mvn package'
       def customImage = docker.build("sampath5/micro")

        / Push the container to the custom Registry /
      customImage.push()
    }
}
}


