server:
  port: 8081
  
spring:
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE
  datasource:
    platform: true
    url: jdbc:h2:mem:orderdb
  cloud:
    config:
      uri: http://localhost:8888
        
method: "paySecurely"


management:
  endpoints:
    web:
      exposure:
        include: "*"

paymentPort: http://localhost:8082/payment/