server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE
  datasource:
    platform: true
    url: jdbc:h2:mem:paymentdb
  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

my:
  greeting: this is a greeting

thirdPartyPort: http://localhost:8083/thirdparty 