node{
  environment {
    registry = "sampath5/orderservice"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
    stages {
        stage('clean') {
            steps {
              sh 'mvn clean package'
              def pom = readMavenPom file:'pom.xml'
               print pom.version
              env.version = pom.version
                
            }
        }
       
        stage('Building image') {
            steps{
                script {
                   dir ('Order') {
                  dockerImage = docker.build registry + "${env.version}"
                }
                }
             }
          }
          stage('Push Image') {
              steps{
                  script {
                      docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                      }
                  }
              }
            }
      }
}
