pipeline{
  //environment {
    //registry = "sampath5/orderservice"
    //registryCredential = 'dockerhub'
    //dockerImage = ''
  //}
  agent any
    stages {
        stage('clean') {
            steps {
              
              
                
            }
        }
       
        stage('Building image') {
            steps{
                script {
                   dir ('Order') {
                     sh 'mvn clean package'
                     def pom = readMavenPom file:'pom.xml'
               print pom.version
              env.version = pom.version
                  dockerImage = docker.build 'sampath5/thirdps' + "${env.version}"
                }
                }
             }
          }
          stage('Push Image') {
              steps{
                  script {
                      docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                      }
                  }
              }
            }
      }
}
